// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upipmzxvuqkxtoyrybpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaXBtenh2dXFreHRveXJ5YnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NjQxODMsImV4cCI6MjA0OTM0MDE4M30.4PAYTHk59_b--1BGVvBG_a2tpECECkhRmt5Cl7iNUpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);